ALTER TABLE "cart_item" DROP CONSTRAINT "fk_cart_item_product_1";
ALTER TABLE "collection_product" DROP CONSTRAINT "fk_collection_product_collection_1";
ALTER TABLE "collection_product" DROP CONSTRAINT "fk_collection_product_product_1";
ALTER TABLE "content_product" DROP CONSTRAINT "fk_content_product_content_1";
ALTER TABLE "content_product" DROP CONSTRAINT "fk_content_product_product_1";
ALTER TABLE "home_new_product" DROP CONSTRAINT "fk_home_new_product_product_1";
ALTER TABLE "home_recommend_product" DROP CONSTRAINT "fk_home_recommend_product_product_1";
ALTER TABLE "order" DROP CONSTRAINT "fk_order_user_1";
ALTER TABLE "order_item" DROP CONSTRAINT "fk_order_item_order_1";
ALTER TABLE "order_item" DROP CONSTRAINT "fk_order_item_product_1";
ALTER TABLE "order_operate_history" DROP CONSTRAINT "fk_order_operate_history_order_1";
ALTER TABLE "order_return_apply" DROP CONSTRAINT "fk_order_return_apply_order_1";
ALTER TABLE "product" DROP CONSTRAINT "fk_product_product_category_1";
ALTER TABLE "product_attribute" DROP CONSTRAINT "fk_product_attribute_product_1";
ALTER TABLE "product_attribute_value" DROP CONSTRAINT "fk_product_attribute_value_product_1";
ALTER TABLE "product_attribute_value" DROP CONSTRAINT "fk_product_attribute_value_product_attribute_1";
ALTER TABLE "product_comment" DROP CONSTRAINT "fk_product_comment_product_1";
ALTER TABLE "product_detail_template_relation" DROP CONSTRAINT "fk_product_detail_template_relation_product_1";
ALTER TABLE "product_detail_template_relation" DROP CONSTRAINT "fk_product_detail_template_relation_product_detail_template_1";
ALTER TABLE "product_picture" DROP CONSTRAINT "fk_product_picture_product_1";
ALTER TABLE "product_sku" DROP CONSTRAINT "fk_product_sku_product_1";
ALTER TABLE "role_permission_relation" DROP CONSTRAINT "fk_role_permission_relation_permission_1";
ALTER TABLE "role_permission_relation" DROP CONSTRAINT "fk_role_permission_relation_role_1";
ALTER TABLE "user_login_history" DROP CONSTRAINT "fk_user_login_history_user_1";
ALTER TABLE "user_payment_type" DROP CONSTRAINT "fk_user_payment_type_user_1";
ALTER TABLE "user_recevie_address" DROP CONSTRAINT "fk_user_recevie_address_user_1";
ALTER TABLE "user_role" DROP CONSTRAINT "fk_user_role_role_1";
ALTER TABLE "user_role" DROP CONSTRAINT "fk_user_role_user_1";

ALTER TABLE "collection" DROP CONSTRAINT "_copy_2";
ALTER TABLE "collection_product" DROP CONSTRAINT "_copy_1";
ALTER TABLE "product_attribute_value" DROP CONSTRAINT "_copy_3";
ALTER TABLE "product_category" DROP CONSTRAINT "_copy_4";

DROP TABLE IF EXISTS "cart_item";
DROP TABLE IF EXISTS "collection";
DROP TABLE IF EXISTS "collection_product";
DROP TABLE IF EXISTS "content";
DROP TABLE IF EXISTS "content_product";
DROP TABLE IF EXISTS "home_new_product";
DROP TABLE IF EXISTS "home_recommend_product";
DROP TABLE IF EXISTS "order";
DROP TABLE IF EXISTS "order_item";
DROP TABLE IF EXISTS "order_operate_history";
DROP TABLE IF EXISTS "order_return_apply";
DROP TABLE IF EXISTS "permission";
DROP TABLE IF EXISTS "product";
DROP TABLE IF EXISTS "product_attribute";
DROP TABLE IF EXISTS "product_attribute_value";
DROP TABLE IF EXISTS "product_category";
DROP TABLE IF EXISTS "product_comment";
DROP TABLE IF EXISTS "product_detail_template";
DROP TABLE IF EXISTS "product_detail_template_relation";
DROP TABLE IF EXISTS "product_picture";
DROP TABLE IF EXISTS "product_sku";
DROP TABLE IF EXISTS "role";
DROP TABLE IF EXISTS "role_permission_relation";
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS "user_login_history";
DROP TABLE IF EXISTS "user_payment_type";
DROP TABLE IF EXISTS "user_recevie_address";
DROP TABLE IF EXISTS "user_role";